# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eegea/optix6/SDK

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eegea/optix6/SDK

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/eegea/optix6/SDK && $(CMAKE_COMMAND) -E cmake_progress_start /home/eegea/optix6/SDK/CMakeFiles /home/eegea/optix6/SDK/mopal/CMakeFiles/progress.marks
	cd /home/eegea/optix6/SDK && $(MAKE) -f CMakeFiles/Makefile2 mopal/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eegea/optix6/SDK/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/eegea/optix6/SDK && $(MAKE) -f CMakeFiles/Makefile2 mopal/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/eegea/optix6/SDK && $(MAKE) -f CMakeFiles/Makefile2 mopal/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/eegea/optix6/SDK && $(MAKE) -f CMakeFiles/Makefile2 mopal/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/eegea/optix6/SDK && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
mopal/CMakeFiles/mopal.dir/rule:
	cd /home/eegea/optix6/SDK && $(MAKE) -f CMakeFiles/Makefile2 mopal/CMakeFiles/mopal.dir/rule
.PHONY : mopal/CMakeFiles/mopal.dir/rule

# Convenience name for target.
mopal: mopal/CMakeFiles/mopal.dir/rule

.PHONY : mopal

# fast build rule for target.
mopal/fast:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/build
.PHONY : mopal/fast

# Convenience name for target.
mopal/CMakeFiles/mopal_s.dir/rule:
	cd /home/eegea/optix6/SDK && $(MAKE) -f CMakeFiles/Makefile2 mopal/CMakeFiles/mopal_s.dir/rule
.PHONY : mopal/CMakeFiles/mopal_s.dir/rule

# Convenience name for target.
mopal_s: mopal/CMakeFiles/mopal_s.dir/rule

.PHONY : mopal_s

# fast build rule for target.
mopal_s/fast:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/build
.PHONY : mopal_s/fast

Opal.o: Opal.cpp.o

.PHONY : Opal.o

# target to build an object file
Opal.cpp.o:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/Opal.cpp.o
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/Opal.cpp.o
.PHONY : Opal.cpp.o

Opal.i: Opal.cpp.i

.PHONY : Opal.i

# target to preprocess a source file
Opal.cpp.i:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/Opal.cpp.i
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/Opal.cpp.i
.PHONY : Opal.cpp.i

Opal.s: Opal.cpp.s

.PHONY : Opal.s

# target to generate assembly for a file
Opal.cpp.s:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/Opal.cpp.s
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/Opal.cpp.s
.PHONY : Opal.cpp.s

Unity.o: Unity.cpp.o

.PHONY : Unity.o

# target to build an object file
Unity.cpp.o:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/Unity.cpp.o
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/Unity.cpp.o
.PHONY : Unity.cpp.o

Unity.i: Unity.cpp.i

.PHONY : Unity.i

# target to preprocess a source file
Unity.cpp.i:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/Unity.cpp.i
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/Unity.cpp.i
.PHONY : Unity.cpp.i

Unity.s: Unity.cpp.s

.PHONY : Unity.s

# target to generate assembly for a file
Unity.cpp.s:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/Unity.cpp.s
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/Unity.cpp.s
.PHONY : Unity.cpp.s

multitransmitter.o: multitransmitter.cpp.o

.PHONY : multitransmitter.o

# target to build an object file
multitransmitter.cpp.o:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/multitransmitter.cpp.o
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/multitransmitter.cpp.o
.PHONY : multitransmitter.cpp.o

multitransmitter.i: multitransmitter.cpp.i

.PHONY : multitransmitter.i

# target to preprocess a source file
multitransmitter.cpp.i:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/multitransmitter.cpp.i
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/multitransmitter.cpp.i
.PHONY : multitransmitter.cpp.i

multitransmitter.s: multitransmitter.cpp.s

.PHONY : multitransmitter.s

# target to generate assembly for a file
multitransmitter.cpp.s:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/multitransmitter.cpp.s
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/multitransmitter.cpp.s
.PHONY : multitransmitter.cpp.s

tests.o: tests.cpp.o

.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/tests.cpp.o
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i

.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/tests.cpp.i
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s

.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/tests.cpp.s
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/tests.cpp.s
.PHONY : tests.cpp.s

timer.o: timer.cpp.o

.PHONY : timer.o

# target to build an object file
timer.cpp.o:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/timer.cpp.o
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/timer.cpp.o
.PHONY : timer.cpp.o

timer.i: timer.cpp.i

.PHONY : timer.i

# target to preprocess a source file
timer.cpp.i:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/timer.cpp.i
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/timer.cpp.i
.PHONY : timer.cpp.i

timer.s: timer.cpp.s

.PHONY : timer.s

# target to generate assembly for a file
timer.cpp.s:
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal.dir/build.make mopal/CMakeFiles/mopal.dir/timer.cpp.s
	cd /home/eegea/optix6/SDK && $(MAKE) -f mopal/CMakeFiles/mopal_s.dir/build.make mopal/CMakeFiles/mopal_s.dir/timer.cpp.s
.PHONY : timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mopal"
	@echo "... mopal_s"
	@echo "... Opal.o"
	@echo "... Opal.i"
	@echo "... Opal.s"
	@echo "... Unity.o"
	@echo "... Unity.i"
	@echo "... Unity.s"
	@echo "... multitransmitter.o"
	@echo "... multitransmitter.i"
	@echo "... multitransmitter.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/eegea/optix6/SDK && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

