//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
// 

#include "ExternalClockScheduler.h"

namespace inet {

Register_Class(ExternalClockScheduler);

ExternalClockScheduler::ExternalClockScheduler() {
    // TODO Auto-generated constructor stub
    t_external=0.0;

}

ExternalClockScheduler::~ExternalClockScheduler() {
    // TODO Auto-generated destructor stub
}

std::string ExternalClockScheduler::info() const {
    return "External Clock Scheduler";
}

cEvent* ExternalClockScheduler::guessNextEvent() {
    return sim->getFES()->peekFirst();

}

cEvent* ExternalClockScheduler::takeNextEvent() {
    if(simTime() <= t_external) {
        while (true) {
            cEvent *event = sim->getFES()->removeFirst();
                if (!event) {
                    //There is no event in the FES: this may happen if events are only generated by the external entity
                    return nullptr;
                    //  throw cTerminationException(E_ENDEDOK);
                }
                if (event->isStale()) {
                    delete event;
                } else {
                    return event;
                }
        }

    } else {
            return nullptr;
    }

}

void ExternalClockScheduler::startRun() {
    t_external=0.0;
}

void ExternalClockScheduler::setExternalTime(simtime_t _t_external) {
    t_external= _t_external;

}

void ExternalClockScheduler::putBackEvent(cEvent* event) {
    sim->getFES()->putBackFirst(event);


}


} /* namespace inet */
